port: 7890
socks-port: 7891
allow-lan: false
mode: Rule
log-level: info

dns:
  enable: true
  listen: 0.0.0.0:1053
  nameserver: [8.8.8.8, 1.1.1.1]

proxies: []

proxy-groups:
  - name: "🚀 Proxy"
    type: select
    proxies:
      - DIRECT

rules: []
